apiVersion: apps/v1
kind: Deployment
metadata:
  name: Mutiverse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Mutiverse
  template:
    metadata:
      labels:
        app: Mutiverse
    spec:
      containers:
        - name: Mutiverse
          image: REPLACE_WITH_IMAGE
          ports:
            - containerPort: 3000
