apiVersion: v1
kind: Pod
metadata:
  name: Mutiverse-pod
  labels:
    app: Mutiverse
spec:
  containers:
    - name: Mutiverse
      image: REPLACE_WITH_IMAGE
      ports:
        - containerPort: 3000
